#!/bin/bash

#
# Put local parameters into here.
#

#
# Admin credentials
#

#export OS_AUTH_URL=http://127.0.0.1:35357/v2.0/
#export OS_USERNAME=admin
#export OS_TENANT_NAME=admin
#export OS_PASSWORD=[ put password here]

#
# Images to upload
#

IMAGES="http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img \
        http://storage.core-os.net/coreos/amd64-generic/dev-channel/coreos_production_openstack_image.img.bz2 \
        http://cloud-images.ubuntu.com/releases/13.04/release/ubuntu-13.04-server-cloudimg-amd64-disk1.img \
        http://download.fedoraproject.org/pub/fedora/linux/releases/19/Images/x86_64/Fedora-x86_64-19-20130627-sda.qcow2 \
        http://knoppix.hostingxtreme.com/KNOPPIX_V7.2.0CD-2013-06-16-EN.iso \
        http://softlayer-dal.dl.sourceforge.net/project/nst/NST/NST%2018-4509/nst-18-4509.i686.iso "


#
# Network objects 
#
floating_ip_start=10.255.75.4
floating_ip_end=10.255.75.253
