#!/bin/bash

#
# Put local parameters into here.
#

#
# Admin credentials
#

#export OS_AUTH_URL=http://127.0.0.1:35357/v2.0/
#export OS_USERNAME=admin
#export OS_TENANT_NAME=admin
#export OS_PASSWORD=[ put password here]

#
# Images to upload
#

IMAGES="http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img \
        http://c250663.r63.cf1.rackcdn.com/ttylinux.tgz \
        http://storage.core-os.net/coreos/amd64-generic/dev-channel/coreos_production_openstack_image.img.bz2 \
        http://cloud-images.ubuntu.com/releases/13.04/release/ubuntu-13.04-server-cloudimg-amd64-disk1.img \
        http://cloud-images.ubuntu.com/releases/14.04/release-20140416.1/ubuntu-14.04-server-cloudimg-amd64-disk1.img \
        http://download.fedoraproject.org/pub/fedora/linux/updates/20/Images/x86_64/Fedora-x86_64-20-20140407-sda.qcow2 \
        http://knoppix.hostingxtreme.com/KNOPPIX_V7.2.0CD-2013-06-16-EN.iso \
        http://hivelocity.dl.sourceforge.net/project/nst/NST/NST%2020-5663/nst-20-5663.i686.iso \
        http://repos.fedorapeople.org/repos/openstack/guest-images/centos-6.5-20140117.0.x86_64.qcow2 \
        http://savanna-files.mirantis.com/savanna-0.3-vanilla-1.2.1-fedora-19.qcow2 \
        "

#
# Network objects 
#
floating_ip_start=10.255.75.4
floating_ip_end=10.255.75.253

dns_server=128.103.200.101
pub_gateway=10.255.75.1
pub_cidr=10.255.75.0/24

#
# Access objects
#
FLOATING_IP_NET_NAME=public
AUTH_KEYS_URL=https://raw.github.com/robparrott/keys/master/parrott-public.pub

